name: L0

on:
  push:
    paths:
      - l0test/**
  pull_request:
    paths:
      - l0test/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{github.repository}}

      - name: Install valgrind, coverage, cmake
        run: |
          sudo apt update
          sudo apt install -y valgrind lcov cmake

      - name: Build
        working-directory: ${{github.workspace}}
        run: |
          cmake -S ${GITHUB_REPOSITORY}/l0test -B build/l0test -DCMAKE_INSTALL_PREFIX="install" -DCMAKE_CXX_FLAGS="--coverage -Wall -Werror"
          cmake --build build/l0test --target install

      - name: Run
        working-directory: ${{github.workspace}}
        run: PATH=${PWD}/install/bin:${PATH} LD_LIBRARY_PATH=${PWD}/install/lib:${LD_LIBRARY_PATH} valgrind --tool=memcheck --log-file=valgrind_log --leak-check=yes --show-reachable=yes --track-fds=yes --fair-sched=try l0test

      - name: Generate coverage
        working-directory: ${{github.workspace}}
        run: |
          lcov -c -o coverage.info -d build/l0test
          genhtml -o coverage coverage.info

      - name: Upload artifacts
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            coverage/
            valgrind_log
          if-no-files-found: warn

# Usage:
# curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
# sudo apt update
# sudo apt -y install docker.io
# sudo bin/act -W .github/workflows/L0.yml -s GITHUB_TOKEN=your-PAT
